### ISSUE TITLE
And again about missing features

### ISSUE THREAD

**Issue by movqword** [ultralight-ux/ultralight-0.9-api#1]
Hello, Adam.

First of all - thanks for your amazing work.

But, as many users ask in previus beta update - very important to add support of **OpenGL** and **Win32**, many (unreal many) games based on this features, i can understand that you see in the future, but we can't wait 5 years while all our players will install X64 version of Windows.

Please keep your good work and not ignore us.

**Comment by adamjs** [comment]
Hi movqword,

Thanks for your feedback.

For future reference, the official issue tracker is here: https://github.com/ultralight-ux/ultralight/issues

I've added the two requests in question to the tracker and you will be delighted to know that both are almost finished and will be included in an upcoming release.
